# Generated by Django 3.2 on 2021-04-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='flat_no',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
