# Generated by Django 3.2 on 2021-04-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210429_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='chlumodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to='')),
            ],
        ),
    ]
