# Generated by Django 3.2 on 2021-04-29 09:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210429_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='place_of_work_doc',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\hichugh\\helperasservice\\cheffy-app-server\\CheffyBackend\\media'), upload_to='place_of_work_doc'),
        ),
    ]
