# Generated by Django 3.2 on 2021-04-29 10:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='place_of_work_doc',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP User\\nativebackend2\\cheffy-app-server\\CheffyBackend\\media'), upload_to='place_of_work_doc'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='qualification_doc',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP User\\nativebackend2\\cheffy-app-server\\CheffyBackend\\media'), upload_to='qualification_doc'),
        ),
    ]
