# Generated by Django 3.2 on 2021-04-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210429_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='place_of_work_doc',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='qualification_doc',
        ),
    ]
